name: Jquery Core Pipeline
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "README.md", "doc/**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@oneteme'
      - run: npm config ls
      - run: npm cache clean --force
      - run: npm install  
      - run: npm run build '@oneteme/jquery-core'
      - run: npm publish ./dist/oneteme/jquery-core --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }})
      - run: npm run build '@oneteme/jquery-apexcharts'
      - run: npm publish ./dist/oneteme/jquery-apexcharts --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }})